packages:
  - packages/*
  - examples/js

allowBuilds:
  '@swc/core': true
  canvas: true
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@lingui/swc-plugin@6.2.0'
  - hono@4.12.22
  - ws@8.21.0
  - lucide-react@1.24.0
  - vite@8.1.4

onlyBuiltDependencies:
  - '@swc/core'
  - canvas
  - esbuild
  - unrs-resolver
