#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'node:fs';
import { basename, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = resolve(__dirname, '..');

const sourceFiles = [
  'src/asset.ts',
  'src/controls.ts',
  'src/chart.ts',
  'src/types.ts',
  'src/schemas.ts',
  'src/codec.ts',
  'src/binary.ts',
];

const [, , outputArg] = process.argv;
const generatedAt = new Date().toISOString();

const sections = sourceFiles.map((relativePath) => {
  const source = readFileSync(resolve(ROOT, relativePath), 'utf8').trimEnd();
  return [
    `## ${basename(relativePath)}`,
    '',
    `Source: [${relativePath}](./${relativePath})`,
    '',
    '```ts',
    source,
    '```',
  ].join('\n');
});

const markdown = [
  '# TenSnap Protocol Type Definitions',
  '',
  `Generated from source files at ${generatedAt}.`,
  '',
  'This file is generated by `pnpm export:types`; edit the TypeScript source files instead.',
  '',
  ...sections,
  '',
].join('\n');

if (outputArg) {
  writeFileSync(resolve(ROOT, outputArg), markdown, 'utf8');
} else {
  process.stdout.write(markdown);
}
