import { z } from 'zod';
import { AssetMetaSchema } from './asset';
import {
  ChartGroupMetadataSchema,
  ChartMetadataSchema,
  ChartUpdateDataSchema,
  ChartUpdateOperationSchema,
} from './chart';
import { ActionSchema, ParameterSchema } from './controls';
import { isEncodedBinaryString } from './binary';

const BinaryPayloadStringSchema = z.string().refine(
  (value) => isEncodedBinaryString(value),
  'Expected a base64 string or a base64 data URL for binary payload data.',
);

const BinaryPayloadDataSchema = z.union([BinaryPayloadStringSchema, z.instanceof(Uint8Array)]);

export const ItemSchema = z.record(z.string(), z.unknown());
export const ItemDiffSchema = z.record(z.string(), z.unknown());
export const ItemKeySchema = z.record(z.string(), z.unknown());
export const PrimitiveItemKeySchema = z.union([z.string(), z.number()]);

/**
 * `metadata_update` carries scenario-wide metadata, including the current
 * simulation time. It replaces the old split between time-step start and end
 * events, and may carry additional simulator-defined metadata fields.
 */
export const MetadataUpdatePayloadSchema = z.object({
  time: z.number().optional(),
}).loose();

/**
 * `state_sync_begin` and `state_sync_end` bracket a simulator replay triggered
 * by `state_sync`. When present, `request_id` is generated by the renderer and
 * echoed by the simulator so initial sync and reconnect transactions can be
 * correlated without making Scenario transport-aware.
 */
export const StateSyncBoundaryPayloadSchema = z.object({
  request_id: z.string().optional(),
});

/** Optional per-action timing buckets used for tick diagnostics. */
export const TickTimingBreakdownSchema = z.object({
  simulate_ms: z.number().nonnegative().optional(),
  communicate_ms: z.number().nonnegative().optional(),
  render_ms: z.number().nonnegative().optional(),
}).catchall(z.number().nonnegative());

/**
 * `action_end` signals completion of one simulator action execution. Simulators
 * should emit state mutations caused by the action before the matching
 * `action_end`. For continuous actions, explicit `continue: false` stops the
 * renderer-driven loop; `tick_id` should echo the renderer-supplied id.
 */
export const ActionEndPayloadSchema = z.object({
  id: z.string(),
  tick_id: z.string().optional(),
  continue: z.boolean().optional(),
  timings: TickTimingBreakdownSchema.optional(),
});

/** `action_delete` removes a renderer-visible action by id. */
export const ActionDeletePayloadSchema = z.object({ id: z.string() });

/**
 * `env_create` creates a scenario environment container. `2d` covers grid-like
 * and graph-like scenes; rendering semantics are expressed by layers.
 */
export const EnvCreatePayloadSchema = z.object({
  id: z.string(),
  type: z.enum(['uniform', '2d']),
});

/** `env_delete` removes a scenario environment container by id. */
export const EnvDeletePayloadSchema = z.object({ id: z.string() });

/**
 * `env_layer_create` creates an environment-local layer with fixed topology and
 * optional metadata. `dependency_layer_ids` is create-time topology; simulators
 * should recreate the layer or environment if dependencies need to change.
 */
export const EnvLayerCreatePayloadSchema = z.object({
  env_id: z.string(),
  layer_id: z.string(),
  layer_type: z.string(),
  dependency_layer_ids: z.record(z.string(), z.string()).optional(),
  data: z.record(z.string(), z.unknown()).optional(),
});

/**
 * `env_layer_update` replaces layer metadata as a whole object. It is not an
 * item diff channel and must not be used to mutate dependency topology.
 */
export const EnvLayerUpdatePayloadSchema = z.object({
  env_id: z.string(),
  layer_id: z.string(),
  data: z.record(z.string(), z.unknown()),
});

/** `env_layer_delete` removes one layer from an environment. */
export const EnvLayerDeletePayloadSchema = z.object({
  env_id: z.string(),
  layer_id: z.string(),
});

/**
 * `item_create` creates layer-owned items. The exact item schema and primary
 * key are provided by the layer registry entry for the target layer type.
 */
export const ItemCreatePayloadSchema = z.object({
  env_id: z.string(),
  layer_id: z.string(),
  items: z.array(ItemSchema),
});

/**
 * `item_update` carries field-level diffs for existing layer-owned items.
 * Diffs must include the layer registry primary key fields so the renderer can
 * identify each target item.
 */
export const ItemUpdatePayloadSchema = z.object({
  env_id: z.string(),
  layer_id: z.string(),
  items: z.array(ItemDiffSchema),
});

/**
 * `item_delete` removes layer-owned items. Single-key layers may delete by
 * primitive id; multi-key layers, such as edge layers keyed by source/target,
 * delete by object keys matching the registry primary key fields.
 */
export const ItemDeletePayloadSchema = z.object({
  env_id: z.string(),
  layer_id: z.string(),
  items: z.union([z.array(PrimitiveItemKeySchema), z.array(ItemKeySchema)]),
});

/** `param_delete` removes a renderer-visible parameter by id. */
export const ParameterDeletePayloadSchema = z.object({ id: z.string() });

/**
 * `param_sync` pushes a simulator-side value correction after an optimistic
 * renderer edit. A simulator should not emit `param_sync` for every accepted
 * `param_change`; it should emit one only when it rejects the edit or coerces it
 * to a different canonical value. Definition changes, including enum option or
 * label-list changes, are sent with full `param_update` payloads instead.
 */
export const ParameterSyncPayloadSchema = z.object({
  id: z.string(),
  value: z.unknown(),
});

/** `chart_delete` removes a chart or chart series by id. */
export const ChartDeletePayloadSchema = z.object({ id: z.string() });

/**
 * `chart_update` carries incremental data points and chart operations such as
 * `clear`. Chart metadata is maintained separately through `chart_create`.
 */
export const ChartUpdatePayloadSchema = z.object({
  updates: z.array(ChartUpdateDataSchema).optional(),
  operations: z.array(ChartUpdateOperationSchema).optional(),
});

export const LogLevelSchema = z.enum(['debug', 'info', 'warning', 'error', 'critical']);

/** `log` is a diagnostic event emitted by either runtime side. */
export const LogPayloadSchema = z.object({
  message: z.string(),
  level: LogLevelSchema.optional(),
  target: z.string().optional(),
  timestamp: z.number().optional(),
  data: z.unknown().optional(),
});

/** `error` reports a protocol-level or runtime error. */
export const ErrorPayloadSchema = z.object({ error: z.string() });

/** `asset_meta` announces cacheable asset descriptors without sending bytes. */
export const AssetMetaPayloadSchema = z.object({
  assets: z.array(AssetMetaSchema),
});

/**
 * `asset_data` sends one asset's bytes. JSON transports carry base64/data URL
 * strings, while binary transports may carry raw `Uint8Array` values.
 */
export const AssetDataPayloadSchema = z.object({
  id: z.string(),
  hash: z.string(),
  mime: z.string(),
  data: BinaryPayloadDataSchema,
});

/** `asset_delete` removes cached renderer-side assets by id. */
export const AssetDeletePayloadSchema = z.object({
  ids: z.array(z.string()),
});

/** `asset_sync` reports the renderer's currently held asset hashes. */
export const AssetSyncPayloadSchema = z.object({
  assets: z.record(z.string(), z.string()),
});

/**
 * `screenshot_request` asks the renderer to capture an environment or chart.
 * Exactly one of `env_id` or `chart_id` should identify the target. `format`
 * defaults to `png`; `quality` is a 0-1 JPEG hint.
 */
export const ScreenshotRequestPayloadSchema = z.object({
  request_id: z.string(),
  env_id: z.string().optional(),
  chart_id: z.string().optional(),
  format: z.enum(['png', 'jpeg']).optional(),
  quality: z.number().min(0).max(1).optional(),
});

/**
 * `screenshot_response` returns a captured image or an error to the simulator.
 * JSON mode uses base64/data URL strings; binary mode may use raw bytes.
 */
export const ScreenshotResponsePayloadSchema = z.object({
  request_id: z.string(),
  data: BinaryPayloadDataSchema.optional(),
  mime: z.string().optional(),
  error: z.string().optional(),
});

/**
 * `state_sync` is sent by the renderer on connect or reconnect. It summarizes
 * renderer-held definitions so the simulator can replay create, update, and
 * delete messages between `state_sync_begin` and `state_sync_end`; simulators
 * do not answer with a reverse `state_sync`.
 */
export const StateSyncRequestSchema = z.object({
  request_id: z.string().optional(),
  parameters: z.array(ParameterSchema),
  actions: z.array(ActionSchema),
  envs: z.array(z.object({
    id: z.string(),
    type: z.string(),
    layers: z.array(z.object({ layer_id: z.string(), layer_type: z.string() })),
  })),
  charts: z.array(ChartMetadataSchema),
});

/**
 * `param_change` is a renderer-side optimistic parameter edit. The simulator is
 * expected to apply accepted values without emitting any sync message. If the
 * edit is rejected or normalized to a different value, the simulator sends
 * `param_sync`; if the parameter definition changes, such as enum options, it
 * sends a full `param_update`.
 */
export const ParameterChangePayloadSchema = z.object({
  id: z.string(),
  value: z.unknown(),
});

/**
 * `action_start` starts one action execution. `continuous` requests a
 * renderer-driven loop, and `tick_id` lets the renderer correlate the eventual
 * `action_end` with one in-flight dispatch.
 */
export const ActionStartPayloadSchema = z.object({
  id: z.string(),
  tick_id: z.string().optional(),
  continuous: z.boolean().optional(),
});

/**
 * Simulator-to-renderer messages mutate renderer-owned Scenario state or ask
 * renderer-side facilities, such as asset cache and screenshots, to do work.
 */
export const SimulatorToRendererMessageSchema = z.object({
  type: z.enum([
    'metadata_update',
    'state_sync_begin',
    'state_sync_end',
    'action_end',
    'action_create',
    'action_update',
    'action_delete',
    'env_create',
    'env_delete',
    'env_layer_create',
    'env_layer_update',
    'env_layer_delete',
    'item_create',
    'item_update',
    'item_delete',
    'param_create',
    'param_update',
    'param_delete',
    'param_sync',
    'chart_create',
    'chart_update',
    'chart_delete',
    'asset_meta',
    'asset_data',
    'asset_delete',
    'screenshot_request',
    'log',
    'error',
  ]),
  payload: z.unknown(),
  timestamp: z.number().optional(),
});

/**
 * Renderer-to-simulator messages express renderer intent, renderer state
 * summary, or renderer-generated output.
 */
export const RendererToSimulatorMessageSchema = z.object({
  type: z.enum([
    'state_sync',
    'param_change',
    'action_start',
    'asset_sync',
    'screenshot_response',
    'error',
  ]),
  payload: z.unknown(),
  timestamp: z.number().optional(),
});

export const AnyProtocolMessageSchema = z.union([
  SimulatorToRendererMessageSchema,
  RendererToSimulatorMessageSchema,
]);

export const getPayloadSchema = (type: string) => {
  switch (type) {
    case 'metadata_update': return MetadataUpdatePayloadSchema;
    case 'state_sync_begin': return StateSyncBoundaryPayloadSchema;
    case 'state_sync_end': return StateSyncBoundaryPayloadSchema;
    case 'action_end': return ActionEndPayloadSchema;
    case 'action_create': return ActionSchema;
    case 'action_update': return ActionSchema;
    case 'action_delete': return ActionDeletePayloadSchema;
    case 'env_create': return EnvCreatePayloadSchema;
    case 'env_delete': return EnvDeletePayloadSchema;
    case 'env_layer_create': return EnvLayerCreatePayloadSchema;
    case 'env_layer_update': return EnvLayerUpdatePayloadSchema;
    case 'env_layer_delete': return EnvLayerDeletePayloadSchema;
    case 'item_create': return ItemCreatePayloadSchema;
    case 'item_update': return ItemUpdatePayloadSchema;
    case 'item_delete': return ItemDeletePayloadSchema;
    case 'param_create': return ParameterSchema;
    case 'param_update': return ParameterSchema;
    case 'param_delete': return ParameterDeletePayloadSchema;
    case 'param_sync': return ParameterSyncPayloadSchema;
    case 'chart_create': return ChartGroupMetadataSchema;
    case 'chart_update': return ChartUpdatePayloadSchema;
    case 'chart_delete': return ChartDeletePayloadSchema;
    case 'asset_meta': return AssetMetaPayloadSchema;
    case 'asset_data': return AssetDataPayloadSchema;
    case 'asset_delete': return AssetDeletePayloadSchema;
    case 'screenshot_request': return ScreenshotRequestPayloadSchema;
    case 'screenshot_response': return ScreenshotResponsePayloadSchema;
    case 'log': return LogPayloadSchema;
    case 'error': return ErrorPayloadSchema;
    case 'state_sync': return StateSyncRequestSchema;
    case 'param_change': return ParameterChangePayloadSchema;
    case 'action_start': return ActionStartPayloadSchema;
    case 'asset_sync': return AssetSyncPayloadSchema;
    default: return z.unknown();
  }
};
